### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by CoderHam** [gauravagerwala/VIT-StudentHandbook#1]
Well, firstly we need to have the drawable circle to be set to a particular size and not vary with the size of the text in it. We need to have different colored circles obviously. Also here are the pictures for the design. Have a look at it. 

![image](https://cloud.githubusercontent.com/assets/11223643/7910770/1827d234-0875-11e5-9c5a-bd504c59d7d7.png)
![image](https://cloud.githubusercontent.com/assets/11223643/7910776/1ccfac62-0875-11e5-9c73-aaa4814b97b5.png)
![image](https://cloud.githubusercontent.com/assets/11223643/7910838/99589a82-0875-11e5-9bcc-e4ce249da483.png)

**Comment by gauravagerwala** [comment]
The circle needs to be oriented relative to the screen size. You cant fix its size.
We will just ensure that all 4 circles are wrapped by width.
Text size will be adjusted automatically according to that.
